# Generated by Django 6.0.7 on 2026-07-24 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('column_names', models.JSONField(help_text="Ordered list of column names to assign to the raw file, left to right — must match the raw file's column count exactly.")),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Short name for this calibration source, e.g. "H2O", "Plazma", "Mike".', max_length=100)),
                ('file', models.FileField(upload_to='calibration_uploads/%Y/%m/')),
                ('name_filter', models.CharField(blank=True, help_text='Optional: keep only rows whose Name contains this substring, e.g. "(M)" or "PT77 Cal" — for files that bundle several overlapping calibration sets.', max_length=100)),
                ('parsed_ok', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='analayzer.calibrationbatch')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='analayzer.instrumentprofile')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.JSONField(default=list)),
                ('k', models.FloatField(blank=True, null=True)),
                ('b', models.FloatField(blank=True, null=True)),
                ('r2', models.FloatField(blank=True, null=True)),
                ('fit_error', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('needs_review', 'Нужна проверка'), ('ok', 'Автоматически подобрано'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='needs_review', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_curves', to=settings.AUTH_USER_MODEL)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curves', to='analayzer.compound')),
                ('raw_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curves', to='analayzer.rawupload')),
            ],
            options={
                'ordering': ['compound__name'],
                'unique_together': {('raw_upload', 'compound')},
            },
        ),
    ]
