# Generated by Django 6.0.7 on 2026-07-25 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analayzer', '0002_seed_instrument_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('conc_min', models.FloatField()),
                ('conc_max', models.FloatField()),
                ('k', models.FloatField(blank=True, null=True)),
                ('b', models.FloatField(blank=True, null=True)),
                ('r2', models.FloatField(blank=True, null=True)),
                ('fit_error', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('needs_review', 'Нужна проверка'), ('ok', 'Автоматически подобрано'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='needs_review', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='analayzer.calibrationcurve')),
            ],
            options={
                'ordering': ['curve', 'index'],
                'unique_together': {('curve', 'index')},
            },
        ),
        migrations.CreateModel(
            name='CalibrationEquivalence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_equivalent', models.BooleanField(blank=True, null=True)),
                ('valid_conc_min', models.FloatField(blank=True, null=True)),
                ('valid_conc_max', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calibration_equivalences', to=settings.AUTH_USER_MODEL)),
                ('curve_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalence_as_a', to='analayzer.calibrationcurve')),
                ('curve_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalence_as_b', to='analayzer.calibrationcurve')),
                ('segment_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='analayzer.calibrationsegment')),
                ('segment_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='analayzer.calibrationsegment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Необязательно: контекст пробы, например материал матрицы.', max_length=100)),
                ('file', models.FileField(upload_to='sample_uploads/%Y/%m/')),
                ('name_filter', models.CharField(blank=True, max_length=100)),
                ('parsed_ok', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='analayzer.samplebatch')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_uploads', to='analayzer.instrumentprofile')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SampleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_compound_name', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('area', models.FloatField(blank=True, null=True)),
                ('is_area', models.FloatField(blank=True, null=True)),
                ('response', models.FloatField(blank=True, null=True)),
                ('computed_conc', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('needs_review', 'Нужна проверка'), ('matched', 'Определено'), ('out_of_range', 'Вне диапазона калибровок'), ('no_calibration', 'Нет подходящей калибровки')], default='needs_review', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_results', to='analayzer.compound')),
                ('matched_segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_results', to='analayzer.calibrationsegment')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analayzer.sampleupload')),
            ],
            options={
                'ordering': ['upload', 'compound__name', 'name'],
            },
        ),
    ]
