# Generated by Django 6.0.7 on 2026-07-26 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analayzer', '0003_calibrationsegment_calibrationequivalence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MergedSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('conc_min', models.FloatField()),
                ('conc_max', models.FloatField()),
                ('k', models.FloatField(blank=True, null=True)),
                ('b', models.FloatField(blank=True, null=True)),
                ('r2', models.FloatField(blank=True, null=True)),
                ('point_count', models.PositiveIntegerField(default=0)),
                ('fit_error', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('needs_review', 'Нужна проверка'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='needs_review', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merged_segments', to='analayzer.compound')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_segments', to=settings.AUTH_USER_MODEL)),
                ('curves', models.ManyToManyField(related_name='merged_segments', to='analayzer.calibrationcurve')),
            ],
            options={
                'ordering': ['compound', 'conc_min'],
            },
        ),
        migrations.AddField(
            model_name='sampleresult',
            name='matched_merged_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_results', to='analayzer.mergedsegment'),
        ),
    ]
